name: Production

on:
  push:
    branches:
      - master

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm test
      - run: npx vercel --token $VERCEL_TOKEN --confirm --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
